import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Code Hunting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
     
      <main className={styles.main}>
        <div className={styles.center}>
            <p>CODE HUNTING</p>
        </div>
        <div className={styles.span}>      
            <span><br/><br/><br/>Code Hunting is a blog website dedicated to software developers, coders and tech enthusiasts. The website provides an array of resources, tips, tutorials, and news to help its readers stay up-to-date with the latest advancements in the tech world. The website's primary focus is on coding, software development and programming languages.<br/><br/>
                    <span>Some of the popular topics covered on Code Hunting  include:</span><br/><br/>
                    <Link href='/blogpost/best-coding-practices'><li>Best coding practices</li></Link>
                    <Link href='/blogpost/Latest-programming-languages-and-frameworks'><li>Latest programming languages and frameworks</li></Link>
                    <Link href='/blogpost/Career-advice-for-software-developers'><li>Career advice for software developers</li></Link>
                    <Link href='/blogpost/Essential-tools-for-coders'><li>Essential tools for coders</li></Link>
                    <Link href='/blogpost/Debugging-and-problem-solving-techniques'><li>Debugging and problem-solving techniques</li></Link>
                    <Link href='/blogpost/Mobile-app-development'><li>Mobile app development</li></Link>
                    <Link href='/blogpost/Web-development'><li>Web development</li></Link>
                    <Link href='/blogpost/Cloud-computing'><li>Cloud computing</li></Link>
                    <Link href='/blogpost/Artificial-intelligence-and-machine-learning'><li>Artificial intelligence and machine learning</li></Link><br/><br/>
                    The blog features articles written by a team of experienced software developers and experts who have a passion for coding and technology. They share their knowledge, experience and best practices to help others improve their coding skills and become better developers. The blog also features guest posts from industry leaders, providing readers with a wider range of perspectives and insights.<br/><br/>

                    In addition to articles, Code Hunting also offers a forum for its community where readers can engage in discussions, ask questions and share their thoughts. The website is updated regularly with new content, ensuring that its readers are always up-to-date with the latest trends and advancements in the tech world.

                    Whether you're a seasoned software developer or just starting out, Code Hunting is a valuable resource for anyone who wants to stay ahead in the tech world. Visit the website today to start exploring the world of coding and technology.
            </span>
        </div> 
      </main>
    </>
  )
}
